# Generated by Django 4.1 on 2023-09-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais_origen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoModular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_auto', models.IntegerField(blank=True, null=True)),
                ('precio_moto', models.IntegerField(blank=True, null=True)),
                ('precio_usuario', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipotramite')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dimensiones', models.TextField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipomodular')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField(max_length=5000)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipomensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('enfermedad', models.ManyToManyField(blank=True, null=True, to='servicios.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Manualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=5000)),
                ('tiempo', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.material')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=5000)),
                ('estado', models.BooleanField(default=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.autor')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.elemento')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=5000)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingredientes', models.TextField(max_length=2000)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('tipoComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipocomida')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.propietario')),
            ],
        ),
    ]
